import Head from 'next/head';

import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';
import { Hero } from '@/components/Hero';
import styles from '@styles/Home.module.scss';

export default function Home() {
    return (
        <>
            <Head>
                <title>Portfolio | Sato Taisei</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={styles.main}>
                <Hero />

                <div className={styles.dummy}>ShowCase</div>
                <div className={styles.dummy}>Timeline</div>
                <div className={styles.dummy}>Contact</div>
            </main>

            <Footer />
        </>
    );
}
