import Head from 'next/head';

import { ContactLinks } from '@/components/ContactLinks';
import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';
import { Heading } from '@/components/Heading';
import { Hero } from '@/components/Hero';
import { Main } from '@/components/Main';
import { ShowCaseList } from '@/components/ShowCase/ShowCaseList';
import { TimelineList } from '@/components/TimelineList';
import styles from '@/styles/Home.module.scss';

export default function Home() {
    return (
        <>
            <Head>
                <title>Portfolio | Sato Taisei</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <Main className={styles.main}>
                <Hero />
                <ShowCaseList />
                <TimelineList />

                <Heading title="Contact" className={styles.heading} />
                <ContactLinks className={styles.contact} />
            </Main>

            <Footer />
        </>
    );
}
