import Head from 'next/head';

import { Contact } from '@/components/Contact';
import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';
import { Hero } from '@/components/Hero';
import { ShowCase } from '@/components/ShowCase';
import { Timeline } from '@/components/Timeline';
import styles from '@styles/Home.module.scss';

export default function Home() {
    return (
        <>
            <Head>
                <title>Portfolio | Sato Taisei</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={styles.main}>
                <Hero className={styles.hero} />
                <ShowCase className={styles.showcase} />
                <Timeline className={styles.timeline} />
                <Contact className={styles.contact} />
            </main>

            <Footer />
        </>
    );
}
